# NumPy Arrays

Package management

In [ ]:
import numpy as np # import NumPy 

Printing integer at single array index

In [4]:
x = np.array([1, 2, 3, 4]) # gen array
print(x[0]) # retrieve integer at index 0

1


Array interval ranges

In [2]:
x = np.arange(1, 7) # integer range 1-7, no step
print(x)

b = np.arange(1,20,2) # integer range 1-20, step size 2
print(b)

[1 2 3 4 5 6]
[ 1  3  5  7  9 11 13 15 17 19]


Reshaping arrays

In [7]:
x = np.arange(1, 7)
z = x.reshape(3, 2) # reshape array at 3 rows, 2 cols
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
b = np.arange(1,41)
w = b.reshape(-1,2) # reshape array of n at x rows, 2 cols (where x = n/col)
print(w)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]
 [25 26]
 [27 28]
 [29 30]
 [31 32]
 [33 34]
 [35 36]
 [37 38]
 [39 40]]


In [11]:
x = np.array([[1, 2], [3, 4], [5, 6]]) # array of grouped integers (3 x 2)
print(x)

z = x.reshape(6) # flatten array (1 x 6)
print(z)

x1 = np.array([[1,2,3],[2,3,4]]) # array of grouped integers (2 x 3)
print(x1)

z1 = x1.reshape(6) # flatten array (1 x 6)
print(z1)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [2 3 4]]
[1 2 3 2 3 4]


Printing integers at array index interval

In [14]:
x = np.arange(1, 10)
print(x)

print(x[0:2]) # print integers at indices 0-2
print(x[5:]) # print integers beginning at index 5
print(x[:2]) # print integers until index 2
print(x[-3:]) # print last 3 integers from end

z = np.arange(1,100)
print(z)

print(z[2:40]) # print integers at indices 2-40

print(z[:50]) # print integers until index 50

print(z[50:]) # print integers beginning at index 50

[1 2 3 4 5 6 7 8 9]
[1 2]
[6 7 8 9]
[1 2]
[7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]


Conditionally printing integers in arrays

In [17]:
x = np.arange(1, 10)
print(x[x<4]) # print integers in array x less than 4

print(x[x>5]) # print integers in array x greater than 4

print(x[x!=6]) # print integers in array x that are not 6

[1 2 3]
[6 7 8 9]
[1 2 3 4 5 7 8 9]


In [18]:
x = np.arange(1, 10)

print(x[(x>5) & (x%2==0)]) # print even numbers greater than 5

print(x[(x<3) & (x%2==0)]) # print even numbers less than 3

[6 8]
[2]
